/**
 *
 * C'est la main frame de notre interface, ainsi il ya le fonction main ici.
 * tous les panneaux seront déclarés ici, lorsque nous appuierons sur les boutons correspondants, le panneau sera affiché
 */
package Dynamic;

import Dynamic.Panel.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

public class MainFrame extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();
    Message p1 = new Message();
    Historique p2 = new Historique();
    Destinataire p3 = new Destinataire();
    Annuaire p4 = new Annuaire();
    Groupe p5 = new Groupe();
    Modifier p6 = new Modifier();
    Supprimer p7 = new Supprimer();
    Relation p8 = new Relation();
 
    public MainFrame() {
        initComponents();
        DynamicPanel.setLayout(layout);
        GridBagConstraints c  = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(p1,c);
        DynamicPanel.add(p2,c);
        DynamicPanel.add(p3,c);
        DynamicPanel.add(p4,c);
        DynamicPanel.add(p5,c);
        DynamicPanel.add(p6,c);
        DynamicPanel.add(p7,c);
        DynamicPanel.add(p8,c);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);   
        p5.setVisible(false); 
        p6.setVisible(false);  
        p7.setVisible(false);
        p8.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EnvoieMsg = new javax.swing.JButton();
        HistoMsg = new javax.swing.JButton();
        AjouteDest = new javax.swing.JButton();
        Annuaire = new javax.swing.JButton();
        Groupe = new javax.swing.JButton();
        ModifDest = new javax.swing.JButton();
        SuppDest = new javax.swing.JButton();
        Relation = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        EnvoieMsg.setText("Envoie un Message");
        EnvoieMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvoieMsgActionPerformed(evt);
            }
        });

        HistoMsg.setText("Historique du mesage");
        HistoMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoMsgActionPerformed(evt);
            }
        });

        AjouteDest.setText("Ajouter Un Destinataire");
        AjouteDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouteDestActionPerformed(evt);
            }
        });

        Annuaire.setText("Annuaire");
        Annuaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnuaireActionPerformed(evt);
            }
        });

        Groupe.setText("Groupes");
        Groupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupeActionPerformed(evt);
            }
        });

        ModifDest.setText("Modifier Un Destinataie");
        ModifDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifDestActionPerformed(evt);
            }
        });

        SuppDest.setText("Supprimer Un Destinataire");
        SuppDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppDestActionPerformed(evt);
            }
        });

        Relation.setText("Relation");
        Relation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AjouteDest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HistoMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnvoieMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Annuaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Groupe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SuppDest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Relation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(EnvoieMsg)
                .addGap(18, 18, 18)
                .addComponent(HistoMsg)
                .addGap(18, 18, 18)
                .addComponent(AjouteDest)
                .addGap(18, 18, 18)
                .addComponent(Annuaire)
                .addGap(18, 18, 18)
                .addComponent(Groupe)
                .addGap(18, 18, 18)
                .addComponent(ModifDest)
                .addGap(18, 18, 18)
                .addComponent(SuppDest)
                .addGap(18, 18, 18)
                .addComponent(Relation)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        DynamicPanel.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnvoieMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvoieMsgActionPerformed
       //panel ENVOIE UN MESSAGE est choisi
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
    }//GEN-LAST:event_EnvoieMsgActionPerformed

    private void HistoMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoMsgActionPerformed
        //panel HISTORIQUE MESSAGE est choisi
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false); 
        p8.setVisible(false);
    
    }//GEN-LAST:event_HistoMsgActionPerformed

    private void AjouteDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouteDestActionPerformed
        //panel AJOUTER UN DESTINATAIRE est choisi
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false); 
        p8.setVisible(false);
    
    }//GEN-LAST:event_AjouteDestActionPerformed

    private void AnnuaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnuaireActionPerformed
        //panel ANNUAIRE est choisi
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
    
    }//GEN-LAST:event_AnnuaireActionPerformed

    private void GroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupeActionPerformed
        //panel GROUPE est choisi
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
        p6.setVisible(false);
        p7.setVisible(false); 
        p8.setVisible(false);
    
    }//GEN-LAST:event_GroupeActionPerformed

    private void ModifDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifDestActionPerformed
        //panel MODIFIER UN DESTINATAIRE est choisi
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(true);
        p7.setVisible(false); 
        p8.setVisible(false);
    
    }//GEN-LAST:event_ModifDestActionPerformed

    private void SuppDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppDestActionPerformed
        //panel SUPPRIMER UN DESTINATAIRE est choisi
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(true);
        p8.setVisible(false);
    
    }//GEN-LAST:event_SuppDestActionPerformed

    private void RelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelationActionPerformed
         //panel RELATION est choisi
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(true);
    }//GEN-LAST:event_RelationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* CREATION DE FRAME ET L'AFFICHAGE DE INTERFACE*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouteDest;
    private javax.swing.JButton Annuaire;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton EnvoieMsg;
    private javax.swing.JButton Groupe;
    private javax.swing.JButton HistoMsg;
    private javax.swing.JButton ModifDest;
    private javax.swing.JButton Relation;
    private javax.swing.JButton SuppDest;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
