/**
 *
 * C'est la classe pour la creation d'une destinataire
 */
package Dynamic.Panel;

import java.sql.*;
import java.sql.SQLException;
import Base.connect;
import java.awt.event.ItemEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;

public class Destinataire extends javax.swing.JPanel {
    /**
     * Creates new form Destinataire
     */
    public Destinataire() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Perso = new javax.swing.JRadioButton();
        Prof = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Nom");

        jLabel2.setText("Prenom");

        jLabel3.setText("Tel");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel4.setText("Les infos de destinataire");

        jLabel6.setText("Mail");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Perso.setText("Personel");
        Perso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersoActionPerformed(evt);
            }
        });

        Prof.setText("Profesionel");
        Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel4)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Perso)
                        .addGap(18, 18, 18)
                        .addComponent(Prof))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(txtTel)
                            .addComponent(txtNom)
                            .addComponent(txtMail))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Perso)
                    .addComponent(Prof))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CreerDest();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CreerDest() {
        //Methode pour creer une destinataire
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        String tel = txtTel.getText();
        String mail = txtMail.getText();
        String type = null;
        Connection conn = null;
        
        if(Prof.isSelected()){
            type = "Professionnel";
        }else if (Perso.isSelected()){
            type = "Personnel";
        }
        
        conn = connect.getConnect(); //connexion base
        try {
            Class.forName("com.mysql.jdbc.Driver");
           if (conn != null) { //si on est bien connecter au BDD
                String sql = "INSERT INTO DESTINATAIRE (id, nom, prenom, tel, mail,type) VALUES (NULL, ?, ?, ?,?,?)";
                PreparedStatement statement = conn.prepareStatement(sql);
                statement.setString(1, nom);
                statement.setString(2, prenom);
                statement.setString(3, tel);
                statement.setString(4, mail);
                statement.setString(5, type);
                String data =  "{'action' : 'newDest', 'nom' : '"+ nom +"', 'prenom ' : '"+ prenom +"', 'num' : '" + tel + "', 'mail' : '" + mail + "', 'type' : '" + type + "'}" ;
                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(null, "Contact Ajouté!" );
                    //Reinitialiser/vider tous les champs
                    txtNom.setText("");
                    txtPrenom.setText("");
                    txtTel.setText("");
                    txtMail.setText("");
                    Prof.setSelected(false);
                    Perso.setSelected(false);
                    ConnServer(data); //connexion au serveur pour envoie JSON
                }
                System.out.println(data);
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("Problem: database driver class");
            ex.printStackTrace();
        } catch (SQLException ex) {
            System.out.println("Problem connexion, verifier login/mdp");
            ex.printStackTrace();
        }  finally {
            if (conn != null) {
                try {
                    conn.close(); //fermer la connexion
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }
    private void ConnServer(String msg){
        try{
		Socket s = new Socket("192.168.43.250", 3000);// send connection request to local machine port 3000	

		System.out.println("connection established"); // va etre afficher si la connection est bien établir		
		
                DataOutputStream out = new DataOutputStream(s.getOutputStream());
		DataInputStream in = new DataInputStream(s.getInputStream());
							
		out.writeUTF(msg/*new String(encrypted)*/);
		String reponse = in.readUTF();
			
		System.out.println(reponse);
	}catch(Exception e){
		System.out.println(e);
                System.out.println("connection KO");
	}
    
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Button RESET
        txtNom.setText("");
        txtPrenom.setText("");
        txtTel.setText("");
        txtMail.setText("");
        Prof.setSelected(false);
        Perso.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /* Il est possible de choisir un seul type de destinataire, soit perso ou prof*/
    private void PersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersoActionPerformed
        if(Perso.isSelected()){
            Prof.setSelected(false);
        }
    }//GEN-LAST:event_PersoActionPerformed

    private void ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfActionPerformed
        if(Prof.isSelected()){
            Perso.setSelected(false);
        }
    }//GEN-LAST:event_ProfActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Perso;
    private javax.swing.JRadioButton Prof;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
